use std::fs;
use std::path::Path;

use super::block_composition_support::*;
use super::*;

pub(super) fn text_files_below_for_runtime(root: &Path) -> String {
    fn visit(path: &Path, out: &mut String) {
        let mut entries = fs::read_dir(path)
            .expect("read generated directory")
            .collect::<Result<Vec<_>, _>>()
            .expect("read generated entries");
        entries.sort_by_key(|entry| entry.path());
        for entry in entries {
            let path = entry.path();
            if path.is_dir() {
                visit(&path, out);
            } else if matches!(
                path.extension().and_then(|value| value.to_str()),
                Some("md" | "yaml" | "json")
            ) {
                out.push_str(&format!("\n--- {} ---\n", path.display()));
                out.push_str(&fs::read_to_string(path).expect("read generated text"));
            }
        }
    }

    let mut out = String::new();
    visit(root, &mut out);
    out
}

fn text_files_below(root: &Path) -> String {
    text_files_below_for_runtime(root)
}

fn compose_two(dir: &Path, review: &Path, fix: &Path, output: &Path, explicit: bool) -> CliRun {
    let review_mount = mount_arg("review", review);
    let fix_mount = mount_arg("fix", fix);
    let output = output.to_str().expect("output path");
    let mut args = vec![
        "instantiate",
        "--mount",
        review_mount.as_str(),
        "--mount",
        fix_mount.as_str(),
        "--set",
        "review.subject=auth",
        "--set",
        "fix.subject=auth",
    ];
    if explicit {
        args.extend([
            "--seam",
            "review.done=fix.entry",
            "--pass",
            "review.report=fix.report",
            "--pass",
            "review.findings=fix.findings",
        ]);
    }
    args.extend(["--output", output]);
    run_compose(dir, &args)
}

/// Two valid blocks deliberately repeat every important local name. Only a
/// semantic, injective qualification pass can materialize and validate both.
/// §FS-rhei-library.3–5 docs/functional-spec/rhei-library.spec.md:109
#[test]
fn direct_composition_qualifies_overlapping_owned_names_and_validates() {
    let dir = unique_temp_dir("blocks-direct-overlap");
    let fixtures = write_composition_fixtures(&dir);
    let output = dir.join("composed");

    let result = compose_two(&dir, &fixtures.review, &fixtures.fix, &output, true);
    assert_success(&result);

    let generated = text_files_below(&output);
    for expected in [
        "m6_review__review",
        "m6_review__done",
        "m3_fix__review",
        "m3_fix__done",
        "m6_review__job",
        "m3_fix__job",
        "**Prior:** Task m6_review__job",
        "runtime/blocks/m6_review__/runtime/report.md",
        "m6_review__primary",
        "m3_fix__primary",
        "m6_review__mock",
        "prompt_template: m6_review__shared",
        "Generated by rhei block compiler v1",
        "review-block",
        "fix-block",
    ] {
        assert!(generated.contains(expected), "missing {expected:?} in:\n{generated}");
    }

    let validate = run_compose(&dir, &["validate", output.to_str().expect("output path")]);
    assert_success(&validate);
    assert!(output.join("prompt_templates/m6_review__shared.md").is_file());
    assert!(output.join("prompt_templates/m3_fix__shared.md").is_file());
}

/// Recursive `use` and direct mounts are one operation. Repeated mounts remain
/// distinct; only seam-consumed exits lose terminality and internal fan-out
/// keeps its owned lane. §FS-rhei-library.2, §FS-rhei-library.4–5
#[test]
fn recursive_and_repeated_mounts_match_direct_control_and_routing() {
    let dir = unique_temp_dir("blocks-recursive-equivalence");
    let fixtures = write_composition_fixtures(&dir);
    let direct = dir.join("direct");
    let curated = dir.join("curated");

    assert_success(&compose_two(&dir, &fixtures.review, &fixtures.fix, &direct, true));
    let curated_run = run_compose(
        &dir,
        &[
            "instantiate",
            fixtures.flow.to_str().expect("flow path"),
            "auth",
            "--output",
            curated.to_str().expect("curated output"),
        ],
    );
    assert_success(&curated_run);

    let direct_machine = read_yaml(&direct.join("states.yaml"));
    let curated_machine = read_yaml(&curated.join("states.yaml"));
    for key in ["states", "transitions", "profiles", "node_policy"] {
        assert_eq!(direct_machine[key], curated_machine[key], "different {key}");
    }

    let states = direct_machine["states"].as_mapping().expect("states mapping");
    let state = |name: &str| states.get(serde_yaml::Value::String(name.into())).expect(name);
    assert_ne!(state("m6_review__done")["final"], true, "consumed exit stays final");
    assert_eq!(state("m6_review__cancelled")["final"], true, "alternate exit changed");
    assert_eq!(state("m3_fix__done")["final"], true, "tail exit changed");
    assert!(state("m6_review__panel")["all_targets"].is_sequence());
    assert_eq!(direct_machine["node_policy"]["by_type"]["m6_review__panelist"], "m6_review__panel");

    let twice = dir.join("twice");
    let first = mount_arg("first", &fixtures.review);
    let second = mount_arg("second", &fixtures.review);
    let repeated = run_compose(
        &dir,
        &[
            "instantiate",
            "--mount",
            first.as_str(),
            "--mount",
            second.as_str(),
            "--output",
            twice.to_str().expect("repeated output"),
        ],
    );
    assert_success(&repeated);
    let repeated = fs::read_to_string(twice.join("states.yaml")).expect("repeated machine");
    assert!(repeated.contains("m5_first__review") && repeated.contains("m6_second__review"));
}

/// Qualified inputs retain normal precedence, listing and dry-run behavior;
/// direct output naming follows mount order. §FS-rhei-library.3
#[test]
fn mounted_inputs_preserve_precedence_listing_and_output_modes() {
    let dir = unique_temp_dir("blocks-inputs");
    let fixtures = write_composition_fixtures(&dir);
    let review = mount_arg("review", &fixtures.review);
    let fix = mount_arg("fix", &fixtures.fix);

    let listed = run_compose(
        &dir,
        &["instantiate", "--mount", review.as_str(), "--mount", fix.as_str(), "--list-inputs"],
    );
    assert_success(&listed);
    assert!(listed.stdout.contains("review.subject") && listed.stdout.contains("fix.subject"));

    write_fixture_file(
        &dir,
        "values.yaml",
        "review:\n  subject: from-values\nfix:\n  subject: from-values\n",
    );
    write_fixture_file(&dir, "subject.txt", "from-file\n");
    let result = run_compose(
        &dir,
        &[
            "instantiate",
            "--mount",
            review.as_str(),
            "--mount",
            fix.as_str(),
            "--values",
            "values.yaml",
            "--set",
            "review.subject=from-set",
            "--set-file",
            "fix.subject=subject.txt",
        ],
    );
    assert_success(&result);
    let output = dir.join("review-fix");
    let generated = text_files_below(&output);
    assert!(generated.contains("Review from-set"), "--set lost:\n{generated}");
    assert!(generated.contains("Fix from-file"), "--set-file lost:\n{generated}");

    let dry_output = dir.join("dry-only");
    let dry = run_compose(
        &dir,
        &[
            "instantiate",
            "--mount",
            review.as_str(),
            "--mount",
            fix.as_str(),
            "--dry-run",
            "--output",
            dry_output.to_str().expect("dry output"),
        ],
    );
    assert_success(&dry);
    assert!(!dry_output.exists(), "dry run wrote its output");
}

/// No mount means the pre-feature grammar and visible identities. This passing
/// baseline guards the strict one-template compatibility boundary.
/// §FS-rhei-library.3–4 docs/functional-spec/rhei-library.spec.md:109
#[test]
fn legacy_instantiation_without_mount_keeps_unqualified_output() {
    let dir = unique_temp_dir("blocks-legacy-identity");
    let fixtures = write_composition_fixtures(&dir);
    let output = dir.join("legacy");
    let result = run_compose(
        &dir,
        &[
            "instantiate",
            fixtures.review.to_str().expect("review path"),
            "--set",
            "subject=auth",
            "--output",
            output.to_str().expect("output path"),
        ],
    );
    assert_success(&result);
    let generated = text_files_below(&output);
    assert!(generated.contains("### Task job:") && generated.contains("path: runtime/report.md"));
    assert!(!generated.contains("m6_review__"), "legacy output was qualified");
}

/// This baseline records the built-in wrapper's public shape before review and
/// fix are extracted. The later extraction may reorganize sources, not these
/// names, controls, paths, placement, or behavior. §FS-rhei-library.7
#[test]
fn changeset_review_public_shape_is_the_compatibility_baseline() {
    let dir = unique_temp_dir("blocks-changeset-baseline");
    let output = dir.join("changeset-review");
    let result = run_compose(
        &dir,
        &[
            "instantiate",
            "changeset-review",
            "HEAD~3",
            "--set",
            "fix_prepare=worktree",
            "--set",
            "fix_commit=commit",
            "--output",
            output.to_str().expect("output path"),
        ],
    );
    assert_success(&result);
    let generated = text_files_below(&output);
    for stable in [
        "### Task coordinate: Coordinate review of HEAD~3",
        "split:",
        "review:",
        "human-review:",
        "prepare-workspace:",
        "final-fix:",
        "commit-fix:",
        "runtime/decisions/{task_id}-final-decision.md",
        "runtime/fixes/{task_id}-final-fix.md",
        "runtime/workspaces/{task_id}.yaml",
        "\"codex\"",
    ] {
        assert!(generated.contains(stable), "lost compatibility identity {stable:?}");
    }
    assert!(output.join("index.rhei.md").is_file());
    assert!(output.join("tasks/01-coordinate.md").is_file());
    assert!(output.join(".agent-grounds/rhei/settings.json").is_file());
}

/// The compatibility wrapper is evidence of extraction only when both halves
/// are independently discoverable and can be recomposed with a real data pass.
/// §FS-rhei-library.7 docs/functional-spec/rhei-library.spec.md:283
#[test]
fn changeset_review_extracted_blocks_recompose_with_a_runtime_decision_pass() {
    let dir = unique_temp_dir("blocks-changeset-extraction");
    for name in ["code-review", "fix"] {
        let detail = run_compose(&dir, &["templates", name, "--json"]);
        assert_success(&detail);
        assert_eq!(
            serde_json::from_str::<serde_json::Value>(&detail.stdout).expect("template JSON")
                ["name"],
            name
        );
    }

    let output = dir.join("recomposed");
    let result = run_compose(
        &dir,
        &[
            "instantiate",
            "--mount",
            "review=code-review",
            "--mount",
            "fix=fix",
            "--set",
            "review.change_ref=HEAD~3",
            "--seam",
            "review.done=fix.entry",
            "--pass",
            "review.decision=fix.decision",
            "--output",
            output.to_str().expect("output path"),
        ],
    );
    assert_success(&result);
    let generated = text_files_below(&output);
    assert!(generated.contains("m6_review__split"));
    assert!(generated.contains("m3_fix__final-fix"));
    assert!(generated.contains("final-decision"), "decision artifact was not lowered");
}
