//! Serialize typed plans without interpreting task prose or fenced examples.
//! §AR-rhei-library.3 §FS-rhei-library.4
use super::*;
use crate::ast::Task;
use std::path::PathBuf;

impl CompiledBlock {
    pub fn files(&self) -> CompileResult<BTreeMap<PathBuf, CompiledFile>> {
        let mut files = self.fragment.files.clone();
        let mut yaml_header = format!(
            "# Generated by rhei block compiler v1; root: {}\n",
            self.fragment.machine.name
        );
        let mut md_header = format!(
            "<!-- Generated by rhei block compiler v1; root: {} -->\n",
            self.fragment.machine.name
        );
        for origin in &self.origins {
            yaml_header.push_str(&format!("# block: {origin}\n"));
            md_header.push_str(&format!("<!-- block: {origin} -->\n"));
        }
        // Prompt bodies are files, and explicit empty all_targets is rejected by
        // the existing loader; omit these serialization-only empty fields.
        let mut encoded =
            serde_yaml::to_value(&self.fragment.machine).map_err(|e| e.to_string())?;
        if let Some(root) = encoded.as_mapping_mut() {
            root.remove("prompt_templates");
        }
        if let Some(states) = encoded.get_mut("states").and_then(serde_yaml::Value::as_mapping_mut)
        {
            for definition in states.values_mut().filter_map(serde_yaml::Value::as_mapping_mut) {
                if definition
                    .get("all_targets")
                    .and_then(serde_yaml::Value::as_sequence)
                    .is_some_and(Vec::is_empty)
                {
                    definition.remove("all_targets");
                }
            }
        }
        if !self.primary_profiles.is_empty() {
            yaml_header.push_str(&format!(
                "# primary profiles folded into {}: {}\n",
                self.fragment
                    .machine
                    .node_policy
                    .as_ref()
                    .map(|p| p.default.as_str())
                    .unwrap_or("flow"),
                self.primary_profiles.iter().cloned().collect::<Vec<_>>().join(", ")
            ));
        }
        let machine = serde_yaml::to_string(&encoded).map_err(|e| e.to_string())?;
        insert(&mut files, "states.yaml".into(), format!("{yaml_header}{machine}"))?;
        let plan = &self.fragment.plan;
        let mut metadata = plan.metadata.clone().unwrap_or_default();
        metadata.insert("structure".into(), serde_yaml::to_value(serde_json::json!({"maxLevels": plan.structure.max_levels, "nodeKinds": plan.structure.node_kinds})).map_err(|e| e.to_string())?);
        let mut index = format!(
            "{md_header}# Rhei: {}\n**States:** {}\n\n---\n{}---\n",
            plan.title,
            plan.states,
            serde_yaml::to_string(&metadata).map_err(|e| e.to_string())?
        );
        for section in &plan.content_sections {
            index.push_str(&format!("\n## {}\n{}\n", section.title, section.content));
        }
        insert(&mut files, "index.rhei.md".into(), index)?;
        for file in &self.fragment.tasks {
            let mut text = md_header.clone();
            for task in &file.tasks {
                emit_task(task, &mut text);
            }
            insert(&mut files, file.path.clone(), text)?;
        }
        if self.fragment.settings.as_object().is_some_and(|m| !m.is_empty()) {
            insert(
                &mut files,
                ".agent-grounds/rhei/settings.json".into(),
                serde_json::to_string_pretty(&self.fragment.settings).map_err(|e| e.to_string())?,
            )?;
        }
        Ok(files)
    }
}

fn insert(
    files: &mut BTreeMap<PathBuf, CompiledFile>,
    path: PathBuf,
    text: String,
) -> CompileResult<()> {
    if files.insert(path.clone(), text.into_bytes().into()).is_some() {
        return Err(format!("generated file collision '{}'", path.display()));
    }
    Ok(())
}

fn emit_task(task: &Task, out: &mut String) {
    out.push_str(&format!(
        "\n{} {} {}: {}\n**State:** {}\n",
        "#".repeat(task.id.depth() + 2),
        heading_kind(&task.kind),
        task.id,
        task.title,
        task.state
    ));
    if !task.prior.is_empty() {
        let refs = task
            .prior
            .iter()
            .enumerate()
            .map(|(i, id)| match task.prior_kinds.get(i).and_then(|k| k.as_deref()) {
                Some(k) => format!("{k} {id}"),
                None => id.to_string(),
            })
            .collect::<Vec<_>>();
        out.push_str(&format!("**Prior:** {}\n", refs.join(", ")));
    }
    if !task.provides.is_empty() {
        out.push_str(&format!("**Provides:** {}\n", task.provides.join(", ")));
    }
    if !task.consumes.is_empty() {
        out.push_str(&format!(
            "**Consumes:** {}\n",
            task.consumes
                .iter()
                .map(|r| format!("{}:{}", r.task, r.name))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    for (field, value) in
        [("Assignee", &task.assignee), ("Model", &task.model), ("Target", &task.target)]
    {
        if let Some(value) = value {
            out.push_str(&format!("**{field}:** {value}\n"));
        }
    }
    out.push('\n');
    out.push_str(&task.content);
    out.push('\n');
    for child in &task.children {
        emit_task(child, out);
    }
}

fn heading_kind(kind: &str) -> String {
    let mut chars = kind.chars();
    chars
        .next()
        .map(|first| first.to_uppercase().collect::<String>() + chars.as_str())
        .unwrap_or_default()
}
